[build]
command = "cd frontend && npm install --legacy-peer-deps && npm run build"
publish = "frontend/.next"

[env]
NODE_VERSION = "20.18.0"
NODE_ENV = "production"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
